CREATE TABLE PRODUCT(
	PRODUCT_ID 			INT 			PRIMARY KEY,
	PRODUCT_NAME 		VARCHAR(20)		NOT NULL UNIQUE,
	PRODUCT_BRAND 		VARCHAR(30) 	NOT NULL,
	PRODUCT_PRICE 		INT 			NOT NULL,
	PRODUCT_INFO		VARCHAR(100) 	NOT NULL,
	PRODUCT_CATEGORY 	VARCHAR(30) 	NOT NULL,
	PRODUCT_CNT			INT DEFAULT 0	NOT NULL,
	PRODUCT_IMG			VARCHAR(500)	NOT NULL
);

SELECT * FROM PRODUCT;

DROP TABLE PRODUCT;