CREATE TABLE REVIEW(
	REVIEW_ID 		INT 			PRIMARY KEY,
	REVIEW_TITLE	VARCHAR(100)	NOT NULL,
	REVIEW_CONTENT	VARCHAR(500)	NOT NULL,
	REVIEW_TIME		TIMESTAMP		NOT NULL,
	REVIEW_SCORE	INT				NOT NULL,
	REVIEW_REPLY	VARCHAR(500),
	MEMBER_ID		VARCHAR(20) 	REFERENCES MEMBER(MEMBER_ID),
	PRODUCT_ID		INT 			REFERENCES PRODUCT(PRODUCT_ID)
);  

SELECT * FROM REVIEW;

DROP TABLE REVIEW;
