CREATE TABLE WISHLIST(
	WISHLIST_ID			INT			PRIMARY KEY,
	WISHLIST_ADDTIME	TIMESTAMP	DEFAULT CURRENT_TIMESTAMP	NOT NULL,
	MEMBER_ID			VARCHAR(20) REFERENCES MEMBER(MEMBER_ID),
	PRODUCT_ID			INT			REFERENCES PRODUCT(PRODUCT_ID)
);

SELECT * FROM WISHLIST;

DROP TABLE WISHLIST;
INSERT INTO WISHLIST (WISHLIST_ID,MEMBER_ID, PRODUCT_ID) VALUES ((SELECT NVL(MAX(WISHLIST_ID),0)+1 FROM WISHLIST),'teemo1', 1001);
